#!/bin/bash

COMMAND=$1
PARAM_1=$2
PARAM_2=$3
DIR_JIKIT=$(cd "$(dirname "$0")";pwd)
DIR_DESKTOP=/users/$(whoami)/Desktop

if [ ! $COMMAND ]; then
  echo -e "
\033[31m JIKIT: Empty command \033[0m
    cp [snippet]      Copy code snippet
    ls [dir]          List filenames to txt
    mp4 [dir]         Batch convert any videos to .mp4
    op [site]         Open a site
    rm [jk-rm.txt]    Remove all files listed in the jk-rm.txt
    run [app]         Run an app
    start [proj]      Start a project
"
  exit
fi

if [ $COMMAND = 'cp' ]; then
  . "$DIR_JIKIT/commands/cp"
elif [ $COMMAND = 'op' ]; then
  . "$DIR_JIKIT/commands/op"
elif [ $COMMAND = 'ls' ]; then
  . "$DIR_JIKIT/commands/ls"
elif [ $COMMAND = 'rm' ]; then
  . "$DIR_JIKIT/commands/rm"
elif [ $COMMAND = 'mp4' ]; then
  . "$DIR_JIKIT/commands/mp4"
else
  echo -e "\033[33m JIKIT: Command '$COMMAND' is not exist \033[0m"
fi

