#!/bin/bash

COMMAND=$1
PARAM_1=$2
PARAM_2=$3
DIR_JIKIT=$(cd "$(dirname "$0")";pwd)
DIR_DESKTOP=/users/$(whoami)/Desktop

if [ ! $COMMAND ]; then
  echo -e "
\033[31m JIKIT: Invalid command \033[0m

    jk cp [snippet]      Copy code snippet
    jk ip                Get local IP address
    jk ls [dir]          List filenames to txt
    jk mp4 [dir]         Batch convert any videos to .mp4
    jk op [site]         Open a site
    jk rm [jk-rm.txt]    Remove all files listed in the jk-rm.txt
    jk run [app]         Run an app
    jk start [proj]      Start a project
"
  exit
fi

commands="cp ip ls mp4 op rm run start"

if [[ "${commands[@]}" =~ $COMMAND ]]; then
  source "$DIR_JIKIT/commands/$COMMAND"
else
  echo -e "\033[33m JIKIT: Command '$COMMAND' is not exist \033[0m"
fi
