#!/bin/bash

if [ ! $1 ]
then
  echo "JK-ERR: Empty command
  cp: [snippet s-name]  copy code snippet
  ls: [dir name]        list filenames to txt
  op: [site s-name]     open a site
  rm: [filenames-list.txt]
  run: [app s-name]      run an app
  start: [proj s-name]     start a project"
  exit
fi

if [ $1 = 'cp' ]
then
  if [ ! $2 ]
  then
    echo 'JK-ERR: Empty snippet name'
  else
    file="/Users/Chisw/WSJ/jikit/src/copy/$2"
    if [ -f $file ]
    then
      pbcopy < $file
      echo "JK-RES: Snippet '$2' copied"
    else
      files=/Users/Chisw/WSJ/jikit/src/copy/*
      echo "JK-ERR: Snippet '$2' is not exist"
      for file in $files
      do
        echo "  $(basename $file)"
      done
    fi
  fi
elif [ $1 = 'op' ]
then
  open https://baidu.com
elif [ $1 = 'ls' ]
then
  stamp=`date +%s`
  targetTxtFile="/Users/chisw/Desktop/list-$stamp.txt"
  touch $targetTxtFile

  currentFiles="./*"
  settedFiles="$2/*"
  targetFiles=$settedFiles

  if [ ! $2 ]
  then
    targetFiles=$currentFiles
  fi

  for file in $targetFiles
  do
    echo $(basename $file) >> $targetTxtFile
  done
  echo "JK-RES: List finished"
elif [ $1 = 'rm' ]
then
  list=`cat $2`
  for file in $list
  do
    rm $file
  done
  exit
else
  echo "JK-ERR: Command '$1' is not exist"
fi

