#!/bin/bash

local_ip=`ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:"​`
echo "${local_ip}" | pbcopy
echo -e "\033[32m JIKIT: Copied successfully ($local_ip) \033[0m"
