#!/bin/bash

if [[ $PARAM_1 = 'tree' ]]; then
  # `brew install tree`
  stamp=`date +%s`
  targetJSON="$DIR_DESKTOP/jk-use-tree-$stamp.json"
  tree --dirsfirst --noreport -n -J -i -s -D --timefmt "%Y-%m-%d %H:%M:%S" -o $targetJSON
elif [[ $PARAM_1 = 'bili' ]]; then
  # `brew install you-get`
  cd ~/Downloads && mkdir $PARAM_2 && cd $PARAM_2 && you-get --playlist $PARAM_3
elif [[ $PARAM_1 = 'clear' ]]; then
  find . -name .DS_Store -type f -delete && dot_clean *
else
  echo -e "\033[33m JIKIT: Use command '$PARAM_1' is not exist \033[0m"
fi
